-- The curated prompt library.
--
-- group_id NULL means global: every group draws from these, and a group can
-- add its own on top. Ids are stable and ordered, so the deterministic daily
-- pick gives the same group the same question on the same day no matter which
-- server answers.
--
-- created_at is 0 rather than a migration-time timestamp: these did not come
-- from any group at any moment, and a real timestamp would sort them in among
-- prompts dads actually wrote.
--
-- Adding to the library later means a new migration, not editing this one.

INSERT INTO prompts (id, group_id, body, author_member_id, active, created_at) VALUES
  ('prm_0001', NULL, 'What did you lose your temper about this week, and what was actually going on underneath it?', NULL, 1, 0),
  ('prm_0002', NULL, 'When did you last raise your voice at your kid? What would you do differently?', NULL, 1, 0),
  ('prm_0003', NULL, 'What behaviour of your kid''s gets under your skin faster than it should?', NULL, 1, 0),
  ('prm_0004', NULL, 'When were you last short with your kid because of something that had nothing to do with them?', NULL, 1, 0),
  ('prm_0005', NULL, 'What''s a punishment you handed out that you regretted an hour later?', NULL, 1, 0),
  ('prm_0006', NULL, 'How do you know when you''re about to lose it? What are your tells?', NULL, 1, 0),
  ('prm_0007', NULL, 'What do you do to cool down, and does it actually work?', NULL, 1, 0),
  ('prm_0008', NULL, 'When did you last apologise to your kid? How did it go?', NULL, 1, 0),
  ('prm_0009', NULL, 'What''s something you said to your kid that you wish you could take back?', NULL, 1, 0),
  ('prm_0010', NULL, 'Is there a time of day when you''re a worse dad? What''s happening then?', NULL, 1, 0),
  ('prm_0011', NULL, 'What did your father do that you swore you''d never do — and have caught yourself doing?', NULL, 1, 0),
  ('prm_0012', NULL, 'What did your father get right that you want to pass on?', NULL, 1, 0),
  ('prm_0013', NULL, 'What did you need from your dad at your kid''s age that you didn''t get?', NULL, 1, 0),
  ('prm_0014', NULL, 'How is your relationship with your father now, and how does it show up in your parenting?', NULL, 1, 0),
  ('prm_0015', NULL, 'What''s a phrase your father used that comes out of your mouth now?', NULL, 1, 0),
  ('prm_0016', NULL, 'If your father could see how you parent, what would he say?', NULL, 1, 0),
  ('prm_0017', NULL, 'What did you learn about being a man from your dad that turned out to be wrong?', NULL, 1, 0),
  ('prm_0018', NULL, 'Who taught you how to be a father, if not your father?', NULL, 1, 0),
  ('prm_0019', NULL, 'What are you doing differently from how you were raised, and is it working?', NULL, 1, 0),
  ('prm_0020', NULL, 'What do you hope your kid says about you to their friends in twenty years?', NULL, 1, 0),
  ('prm_0021', NULL, 'When did you last give your kid your full attention, with no phone in the room?', NULL, 1, 0),
  ('prm_0022', NULL, 'What does your kid do to get your attention when they can''t get it?', NULL, 1, 0),
  ('prm_0023', NULL, 'How much of your time with your kid this week was actually spent with them?', NULL, 1, 0),
  ('prm_0024', NULL, 'What''s the last thing your kid told you that you didn''t really listen to?', NULL, 1, 0),
  ('prm_0025', NULL, 'When did you last let your kid finish a story without hurrying them along?', NULL, 1, 0),
  ('prm_0026', NULL, 'What''s your phone costing you at home?', NULL, 1, 0),
  ('prm_0027', NULL, 'What did you do together this week that had no purpose other than being together?', NULL, 1, 0),
  ('prm_0028', NULL, 'When you get home, what are the first five minutes like?', NULL, 1, 0),
  ('prm_0029', NULL, 'What''s a small ritual you have with your kid, and where did it come from?', NULL, 1, 0),
  ('prm_0030', NULL, 'When did you last be bored together on purpose?', NULL, 1, 0),
  ('prm_0031', NULL, 'What rule in your house do you not actually believe in?', NULL, 1, 0),
  ('prm_0032', NULL, 'Where are you inconsistent, and what does your kid do with that?', NULL, 1, 0),
  ('prm_0033', NULL, 'What''s a boundary you held this week that was hard to hold?', NULL, 1, 0),
  ('prm_0034', NULL, 'When did you cave because you were tired?', NULL, 1, 0),
  ('prm_0035', NULL, 'What are you afraid will happen if you''re strict?', NULL, 1, 0),
  ('prm_0036', NULL, 'What are you afraid will happen if you''re soft?', NULL, 1, 0),
  ('prm_0037', NULL, 'How do you and your partner disagree about discipline in front of the kids?', NULL, 1, 0),
  ('prm_0038', NULL, 'What consequence has actually worked, and why do you think it did?', NULL, 1, 0),
  ('prm_0039', NULL, 'What are you still punishing that you should probably let go?', NULL, 1, 0),
  ('prm_0040', NULL, 'When did your kid last change your mind about a rule?', NULL, 1, 0),
  ('prm_0041', NULL, 'What are you most afraid of for your kid?', NULL, 1, 0),
  ('prm_0042', NULL, 'What are you afraid you''re doing to them without noticing?', NULL, 1, 0),
  ('prm_0043', NULL, 'What keeps you up at night about your family?', NULL, 1, 0),
  ('prm_0044', NULL, 'What worries you about your kid that you''ve never said out loud?', NULL, 1, 0),
  ('prm_0045', NULL, 'What do you think your kid is scared of, and have you asked?', NULL, 1, 0),
  ('prm_0046', NULL, 'What''s the worst-case scenario you catch yourself imagining?', NULL, 1, 0),
  ('prm_0047', NULL, 'How much of your parenting is driven by fear?', NULL, 1, 0),
  ('prm_0048', NULL, 'What did you used to worry about that turned out to be nothing?', NULL, 1, 0),
  ('prm_0049', NULL, 'What would you do if your kid told you something that frightened you?', NULL, 1, 0),
  ('prm_0050', NULL, 'Is there something you''re avoiding dealing with because it''s too hard?', NULL, 1, 0),
  ('prm_0051', NULL, 'How is work showing up at home right now?', NULL, 1, 0),
  ('prm_0052', NULL, 'What are you modelling about work for your kid?', NULL, 1, 0),
  ('prm_0053', NULL, 'When did you last choose work over your family, and was it the right call?', NULL, 1, 0),
  ('prm_0054', NULL, 'What do you want your kid to understand about money?', NULL, 1, 0),
  ('prm_0055', NULL, 'What are you providing that your kid didn''t ask for?', NULL, 1, 0),
  ('prm_0056', NULL, 'What would your kid say your job is?', NULL, 1, 0),
  ('prm_0057', NULL, 'If you had one more hour a day, where would it honestly go?', NULL, 1, 0),
  ('prm_0058', NULL, 'What are you sacrificing, and who decided that trade?', NULL, 1, 0),
  ('prm_0059', NULL, 'What does ''a good provider'' mean to you, and who taught you that?', NULL, 1, 0),
  ('prm_0060', NULL, 'Are you tired, or are you burnt out? What''s the difference for you right now?', NULL, 1, 0),
  ('prm_0061', NULL, 'How are you and your partner doing at parenting as a team?', NULL, 1, 0),
  ('prm_0062', NULL, 'What do you undermine in your partner without meaning to?', NULL, 1, 0),
  ('prm_0063', NULL, 'When did you last back your partner up in front of the kids when you disagreed?', NULL, 1, 0),
  ('prm_0064', NULL, 'What does your partner do with the kids that you couldn''t?', NULL, 1, 0),
  ('prm_0065', NULL, 'What conversation about the kids do you keep avoiding with your partner?', NULL, 1, 0),
  ('prm_0066', NULL, 'How much of the invisible work at home are you actually carrying?', NULL, 1, 0),
  ('prm_0067', NULL, 'What did your kid see this week about how you treat their other parent?', NULL, 1, 0),
  ('prm_0068', NULL, 'When did you and your partner last talk about something other than logistics?', NULL, 1, 0),
  ('prm_0069', NULL, 'What are you modelling about relationships?', NULL, 1, 0),
  ('prm_0070', NULL, 'If you''re parenting apart, what''s hardest about it right now?', NULL, 1, 0),
  ('prm_0071', NULL, 'What''s your kid interested in that you don''t understand?', NULL, 1, 0),
  ('prm_0072', NULL, 'What does your kid do better than you?', NULL, 1, 0),
  ('prm_0073', NULL, 'Who is your kid becoming, and how do you feel about it?', NULL, 1, 0),
  ('prm_0074', NULL, 'What do you love about your kid that has nothing to do with you?', NULL, 1, 0),
  ('prm_0075', NULL, 'When did you last see your kid be kind when nobody made them?', NULL, 1, 0),
  ('prm_0076', NULL, 'What''s your kid struggling with that they haven''t told you about?', NULL, 1, 0),
  ('prm_0077', NULL, 'How is your kid different from who you expected them to be?', NULL, 1, 0),
  ('prm_0078', NULL, 'What do you and your kid disagree about?', NULL, 1, 0),
  ('prm_0079', NULL, 'What does your kid need from you right now that they can''t ask for?', NULL, 1, 0),
  ('prm_0080', NULL, 'When did you last change your mind about your kid?', NULL, 1, 0),
  ('prm_0081', NULL, 'Whose parenting do you compare yourself to, and why them?', NULL, 1, 0),
  ('prm_0082', NULL, 'What do you want other people to think about you as a dad?', NULL, 1, 0),
  ('prm_0083', NULL, 'What are you doing for your kid that''s really for you?', NULL, 1, 0),
  ('prm_0084', NULL, 'How much of your kid''s success do you take personally?', NULL, 1, 0),
  ('prm_0085', NULL, 'What would it mean if your kid turned out ordinary?', NULL, 1, 0),
  ('prm_0086', NULL, 'When did you last feel like a failure as a dad?', NULL, 1, 0),
  ('prm_0087', NULL, 'When did you last feel like you got it right?', NULL, 1, 0),
  ('prm_0088', NULL, 'What part of your identity did you lose when you became a father?', NULL, 1, 0),
  ('prm_0089', NULL, 'What do you miss about who you were before kids?', NULL, 1, 0),
  ('prm_0090', NULL, 'What has fatherhood given you that you didn''t expect?', NULL, 1, 0),
  ('prm_0091', NULL, 'What''s one thing you''d change about how you parent, starting tomorrow?', NULL, 1, 0),
  ('prm_0092', NULL, 'Where do you need help right now?', NULL, 1, 0),
  ('prm_0093', NULL, 'What advice do you keep getting that you keep ignoring?', NULL, 1, 0),
  ('prm_0094', NULL, 'What''s working right now that you should do more of?', NULL, 1, 0),
  ('prm_0095', NULL, 'What have you got better at in the last year?', NULL, 1, 0),
  ('prm_0096', NULL, 'What do you need to forgive yourself for?', NULL, 1, 0),
  ('prm_0097', NULL, 'Who in your life tells you the truth about your parenting?', NULL, 1, 0),
  ('prm_0098', NULL, 'What would you tell a new dad that nobody told you?', NULL, 1, 0),
  ('prm_0099', NULL, 'What''s the hardest thing about being a father that nobody warns you about?', NULL, 1, 0),
  ('prm_0100', NULL, 'If nothing changed for the next five years, would that be alright?', NULL, 1, 0);
