/**
 * Every cryptographic primitive the app uses, in one place.
 *
 * Two very different secrets live here and must not be confused:
 *   - the invite code: low entropy, typed by a human, shared by five friends.
 *     Slow-hashed with PBKDF2 so that guessing it costs real time.
 *   - the device token: 256 random bits generated by us. HMAC is the right
 *     tool; a slow KDF over high-entropy input buys nothing and would tax
 *     every request.
 */

const PBKDF2_ITERATIONS = 120_000;

const encoder = new TextEncoder();

export function base64url(bytes: ArrayBuffer | Uint8Array): string {
  const view = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
  let binary = '';
  for (const byte of view) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

export function fromBase64url(value: string): Uint8Array {
  const padded = value.replace(/-/g, '+').replace(/_/g, '/');
  const binary = atob(padded + '='.repeat((4 - (padded.length % 4)) % 4));
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

/** 256 bits of randomness, url-safe. Used for device tokens and row ids. */
export function randomToken(bytes = 32): string {
  return base64url(crypto.getRandomValues(new Uint8Array(bytes)));
}

/**
 * Constant-time comparison. A plain `===` on a secret leaks its prefix through
 * timing; that matters most for the invite code, which is the only thing
 * standing between the group and a stranger.
 */
export function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

/**
 * Invite codes are passphrases friends say out loud. Case, surrounding space
 * and doubled spaces must never be the reason a dad cannot get in.
 */
export function normalizeInviteCode(code: string): string {
  return code.trim().toLowerCase().replace(/\s+/g, ' ');
}

export async function hashInviteCode(code: string, salt: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    'raw',
    encoder.encode(normalizeInviteCode(code)),
    'PBKDF2',
    false,
    ['deriveBits'],
  );
  const bits = await crypto.subtle.deriveBits(
    {
      name: 'PBKDF2',
      hash: 'SHA-256',
      salt: encoder.encode(salt),
      iterations: PBKDF2_ITERATIONS,
    },
    key,
    256,
  );
  return base64url(bits);
}

export async function verifyInviteCode(
  code: string,
  salt: string,
  expectedHash: string,
): Promise<boolean> {
  return timingSafeEqual(await hashInviteCode(code, salt), expectedHash);
}

async function hmacKey(secret: string): Promise<CryptoKey> {
  return crypto.subtle.importKey(
    'raw',
    encoder.encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign'],
  );
}

export async function hmac(secret: string, message: string): Promise<string> {
  const signature = await crypto.subtle.sign(
    'HMAC',
    await hmacKey(secret),
    encoder.encode(message),
  );
  return base64url(signature);
}

/**
 * A device token identifies a browser, not a person, and is worth stealing:
 * anyone holding one can rejoin as that dad. Only its HMAC reaches the
 * database, so a dump of `members` hands an attacker nothing usable.
 */
export async function hashDeviceToken(secret: string, token: string): Promise<string> {
  return hmac(secret, `device:${token}`);
}
